// Workshop-prep tool: build db/seed.sql from the RAGmonsters source dataset.
//
// Why this exists:
// - The RAGmonsters source ships with a psql-specific multi-file import flow
//   (`\i` directives, `SET search_path TO ragmonsters, public`, etc.).
// - PGlite executes SQL via `db.exec()`, which doesn't understand `\i`, and
//   the deprecated official pg-mcp expects tables in `public`, not a custom
//   schema. We flatten everything into one self-contained seed.sql that
//   creates the RAGmonsters tables directly in `public`.
//
// This script is NOT part of the workshop participant flow. It runs at prep
// time (now), in the talk repo where the RAGmonsters source sits at the repo
// root (one level above workshop-content/). It writes the generated seed
// into db/seed.sql, which IS shipped to participants. Re-run when the
// RAGmonsters source changes.
//
//   cd pglite && bun run build:seed
//
// Path math: from pglite/scripts/, RAGmonsters is three
// levels up (scripts → pglite → workshop-content → repo root → RAGmonsters).

import { readFile, writeFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";

const SOURCE = resolve(import.meta.dir, "..", "..", "..", "RAGmonsters", "postgresql");
const OUT = resolve(import.meta.dir, "..", "db", "seed.sql");

// Strip the schema-management lines that only make sense in a multi-schema
// psql session. The remaining DDL creates tables in `public`, which is what
// the deprecated pg-mcp introspects.
function clean(sql: string): string {
  return sql
    .replace(/SET\s+search_path[^;]*;\s*\n?/gi, "")
    .replace(/DROP\s+SCHEMA[^;]*;\s*\n?/gi, "")
    .replace(/CREATE\s+SCHEMA[^;]*;\s*\n?/gi, "");
}

const schema = clean(await readFile(resolve(SOURCE, "ragmonsters_schema.sql"), "utf8"));

// Extract the categories + subcategories INSERT blocks from
// import_all_monsters.sql. They live between psql \echo directives.
const importAll = await readFile(resolve(SOURCE, "import_all_monsters.sql"), "utf8");

const catMatch = importAll.match(/INSERT INTO categories[\s\S]*?ON CONFLICT[^;]*;/);
const subcatMatch = importAll.match(/INSERT INTO subcategories[\s\S]*?ON CONFLICT[^;]*;/);
if (!catMatch || !subcatMatch) {
  throw new Error("Could not locate categories/subcategories blocks in import_all_monsters.sql");
}
const refdata = `${catMatch[0]}\n\n${subcatMatch[0]}\n`;

// Read every monster file in alphabetical order. clean() strips the per-file
// `SET search_path` line; the rest of each file is pure INSERT + DO block.
const datasetDir = resolve(SOURCE, "dataset");
const files = (await readdir(datasetDir))
  .filter((f) => f.endsWith(".sql"))
  .sort();

const monsters: string[] = [];
for (const f of files) {
  const sql = clean(await readFile(resolve(datasetDir, f), "utf8"));
  monsters.push(`-- ===== ${f} =====\n${sql}`);
}

// Idempotent boot: drop everything before recreating, in dependency order.
const dropAll = `\
-- Idempotency: drop in dependency order before recreating.
DROP TABLE IF EXISTS
  hindrances,
  augments,
  flaws,
  abilities,
  keywords,
  questworlds_stats,
  monsters,
  subcategories,
  categories
CASCADE;
`;

const header = `\
-- RAGmonsters seed for the workshop's shared PGlite (steps 02, 03, …).
-- AUTOGENERATED — do not edit by hand.
-- Source: ../../../RAGmonsters/postgresql/ (relative to pglite/scripts/)
-- Regenerate with:  cd pglite && bun run build:seed
-- Monsters: ${files.length}
`;

const seed = [
  header,
  dropAll,
  "-- ===== Schema =====",
  schema,
  "-- ===== Reference data (categories + subcategories) =====",
  refdata,
  "-- ===== Monsters =====",
  ...monsters,
].join("\n");

await writeFile(OUT, seed);
console.log(`wrote ${OUT}`);
console.log(`  ${(seed.length / 1024).toFixed(1)} KB across ${files.length} monsters`);
